spring:
  liquibase:
#    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

